#!/usr/bin/with-contenv sh

# Installation UUID must be informed
if [ -z "$DASPANEL_SYS_UUID" ]; then
    echo "***"
    echo "ERROR: You must set the env variable DASPANEL_SYS_UUID to a valid UUID"
    echo "***"
    exit 1
fi

if [ ! -d "/etc/caddy" ]; then
    mkdir -p /etc/caddy
fi

export DASPANEL_SYS_HOSTNAME=`cat /opt/daspanel/data/$DASPANEL_SYS_UUID/db/sysconfig.json | /usr/bin/jq -r '.sys.hostname'`

log() {
  if [[ "$@" ]]; then echo "[`date +'%Y-%m-%d %T'`] $@";
  else echo; fi
}

if [ ! -d "/opt/daspanel/log/$DASPANEL_SYS_UUID/caddy" ]; then
	mkdir -p /opt/daspanel/log/$DASPANEL_SYS_UUID/caddy
fi

# Configure caddy
/usr/bin/gomplate -d cfg=file:///opt/daspanel/data/$DASPANEL_SYS_UUID/db/sysconfig.json \
  < /opt/daspanel/conf-templates/daspanel-services/caddy/caddyfile.tmpl \
  > /etc/caddy/caddyfile

# secure daspanel
chown -R daspanel:daspanel /opt/daspanel/data
chown -R daspanel:daspanel /opt/daspanel/log

